spring:
  datasource:
    url: jdbc:sqlite:project3.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: your.custom.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  defer-datasource-initialization: true
