spring:
  datasource:
    url: jdbc:sqlite:project3.db
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  defer-datasource-initialization: true
